development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: t1_dev
  username: postgres
  password: 12345
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: t1_test
  username: postgres
  password: 12345
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: t1_prod
  username: postgres
  password: 12345
  host: localhost
